server:
  port: 8080
spring:
  application:
    name: git_minus
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/repo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  mvc:
    cors:
      allowed-origins: http://localhost:7070
      allowed-methods: GET,POST,HEAD,PUT,DELETE,OPTIONS
      allowed-headers: Content-Type
      allow-credentials: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 53741576@qq.com
    password: fdjsjbmpfsrgbhdc
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  mybatis-plus:
    configuration:
      #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: ASSIGN_ID
        is-transactional: true
ftp:
  protocol: sftp
  port: 22
  address: 47.120.10.89
  username: root
  password: Long.0331
  config:
    StrictHostKeyChecking: no
remote-repo-path: /mydata/git_repo
